use anyhow::Result;
use chrono::Utc;
use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Arc;
use tokio::sync::{broadcast, mpsc};
use uuid::Uuid;

use crate::db::SwarmStore;
use crate::events::{AgentOutputType, SwarmEvent};
use crate::llm::{MultiProviderClient, ModelTier};
use crate::persona_loader::PersonaCatalog;
use crate::pokeball::Pokeball;
use pokedex_mempalace::MemPalace;
use pokedex_tools::{Tool, ToolContext, mem_palace_tool::MEM_PALACE_REGISTRY};
use pokedex_core::cost::CostTracker;
use pokedex_core::Settings;
use pokedex_query::{run_query_loop, QueryConfig, QueryOutcome};

// â”€â”€â”€ Orchestrator Configuration â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// â”€â”€â”€ Orchestrator Configuration â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

pub struct OrchestratorConfig {
    pub event_channel_buffer: usize,
    pub data_dir_name: String,
    pub swarms_subdir: String,
    pub default_max_concurrency: usize,
    pub spawn_stagger: Duration,
    pub batch_save_interval: usize,
    pub progress_report_interval: usize,
}

impl Default for OrchestratorConfig {
    fn default() -> Self {
        use std::time::Duration;
        Self {
            event_channel_buffer: env::var("SWARM_EVENT_BUFFER").ok().and_then(|s| s.parse().ok()).unwrap_or(1024),
            data_dir_name: env::var("POKEDEX_DATA_DIR").unwrap_or_else(|_| ".pokedex".to_string()),
            swarms_subdir: env::var("POKEDEX_SWARMS_SUBDIR").unwrap_or_else(|_| "swarms".to_string()),
            default_max_concurrency: env::var("SWARM_MAX_CONCURRENCY").ok().and_then(|s| s.parse().ok()).unwrap_or(10),
            spawn_stagger: Duration::from_millis(env::var("SWARM_STAGGER_MS").ok().and_then(|s| s.parse().ok()).unwrap_or(500)),
            batch_save_interval: env::var("SWARM_SAVE_INTERVAL").ok().and_then(|s| s.parse().ok()).unwrap_or(50),
            progress_report_interval: env::var("SWARM_REPORT_INTERVAL").ok().and_then(|s| s.parse().ok()).unwrap_or(25),
        }
    }
}

/// The current status/phase of a swarm.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SwarmPhase {
    /// Generating the manifest: understanding the goal, planning roles
    Manifest,
    /// Populating the swarm with agents matched to personas
    PopulatingAgents,
    /// Agents are actively working and collaborating (live LLM execution)
    Collaborating,
    /// Generating the final report from agent outputs
    ReportGeneration,
    /// Swarm execution completed successfully
    Completed,
    /// Swarm failed
    Failed,
}

impl std::fmt::Display for SwarmPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Manifest => write!(f, "manifest"),
            Self::PopulatingAgents => write!(f, "populating_agents"),
            Self::Collaborating => write!(f, "collaborating"),
            Self::ReportGeneration => write!(f, "report_generation"),
            Self::Completed => write!(f, "completed"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

/// A complete swarm instance with its agents and state.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Swarm {
    pub id: Uuid,
    pub goal: String,
    pub phase: SwarmPhase,
    pub agents: Vec<Pokeball>,
    pub manifest: Option<SwarmManifest>,
    pub communication_log: Vec<SwarmEvent>,
    pub report: Option<String>,
    pub created_at: chrono::DateTime<Utc>,
    pub completed_at: Option<chrono::DateTime<Utc>>,
    /// Tracks which agent is currently working or next in line (for resumption)
    #[serde(default)]
    pub current_agent_index: usize,
}

/// The plan generated by the orchestrator for how to staff and execute the goal.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SwarmManifest {
    /// Autonomous project name (max 3 words)
    pub project_name: String,
    pub orchestrator_instructions: String,
    pub agent_roles: Vec<AgentRoleBlueprint>,
    pub execution_strategy: String,
}

/// Blueprint for an agent role before it's matched to a persona.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AgentRoleBlueprint {
    pub name: String,
    pub role: String,
    pub task_description: String,
    /// Legacy: specific model name hint
    #[serde(default)]
    pub model_hint: Option<String>,
    /// MiroFish: model tier for intelligent routing (simulation/general/research/expert)
    #[serde(default)]
    pub model_tier: Option<String>,
    /// Number of replicas to spawn for this archetype (scaled mode)
    #[serde(default)]
    pub replica_count: Option<usize>,
    #[serde(default)]
    pub collaborates_with: Vec<String>,
}

/// The main orchestrator that coordinates swarm lifecycle.
pub struct SwarmOrchestrator {
    /// Persistent storage for swarms
    pub store: Arc<SwarmStore>,
    /// Persona catalog from agency-agents library
    pub catalog: Arc<PersonaCatalog>,
    /// LLM client for swarm reasoning (multi-provider with fallback)
    pub llm: Arc<MultiProviderClient>,
    /// Event broadcaster for WebSocket clients
    pub event_tx: broadcast::Sender<SwarmEvent>,
    /// Path to the library directory
    pub library_path: PathBuf,
    /// MemPalace for long-term agent memory
    pub mempalace: Arc<MemPalace>,
    /// Core API client for agentic execution (supports tools/streaming)
    pub core_api: Arc<pokedex_api::MultiProviderClient>,
    /// Tools available for agentic execution
    pub tools: Arc<Vec<Box<dyn Tool>>>,
    /// Tracker for budget/cost monitoring
    pub cost_tracker: Arc<CostTracker>,
    /// Orchestrator-specific configuration
    pub config: OrchestratorConfig,
}

impl SwarmOrchestrator {
    /// Create a new orchestrator with the given library path.
    pub async fn new(
        library_path: PathBuf,
        core_api: Arc<pokedex_api::MultiProviderClient>,
        tools: Arc<Vec<Box<dyn Tool>>>,
        cost_tracker: Arc<CostTracker>,
    ) -> Result<Self> {
        let config = OrchestratorConfig::default();
        let catalog = PersonaCatalog::load(&library_path)?;
        let (event_tx, _) = broadcast::channel(config.event_channel_buffer);

        // Resolution for persistence path
        let data_dir = match dirs::home_dir() {
            Some(h) => h.join(&config.data_dir_name).join(&config.swarms_subdir),
            None => PathBuf::from(&config.swarms_subdir),
        };
        let store = Arc::new(SwarmStore::new(data_dir.clone()).await?);
        
        // Initialize Multi-Provider LLM Client (Gemini + Copilot with discovery & Load Balancing)
        let llm = Arc::new(MultiProviderClient::new().await);

        // Default MemPalace (legacy/backup)
        let palace_path = data_dir.join("mempalace.db");
        let mempalace = Arc::new(MemPalace::new(&palace_path)?);

        Ok(Self {
            library_path,
            store,
            catalog: Arc::new(catalog),
            llm,
            event_tx,
            mempalace,
            core_api,
            tools,
            cost_tracker,
            config,
        })
    }

    /// Create a new swarm from a user's goal prompt.
    pub async fn create_swarm(&self, goal: String) -> Result<Uuid> {
        let swarm_id = Uuid::new_v4();
        let now = Utc::now();

        let swarm = Swarm {
            id: swarm_id,
            goal: goal.clone(),
            phase: SwarmPhase::Manifest,
            agents: Vec::new(),
            manifest: None,
            communication_log: Vec::new(),
            report: None,
            created_at: now,
            completed_at: None,
        };

        self.store.save(&swarm).await?;

        // Broadcast creation event
        let _ = self.event_tx.send(SwarmEvent::SwarmCreated {
            swarm_id,
            goal,
            timestamp: now,
        });

        Ok(swarm_id)
    }

    /// Run the full swarm execution pipeline (live mode).
    /// This is the main entry point called after create_swarm.
    pub async fn execute_swarm(&self, swarm_id: Uuid) -> Result<()> {
        // Phase 1: Generate manifest
        self.generate_manifest(swarm_id).await?;

        // Phase 2: Populate agents
        self.populate_agents(swarm_id).await?;

        // Phase 3: Collaboration (Live implementation)
        if let Err(e) = self.run_collaboration(swarm_id).await {
            self.transition_phase(swarm_id, SwarmPhase::Failed).await.ok();
            self.cleanup_project_if_empty(swarm_id).await.ok();
            return Err(e);
        }

        // Phase 4: Report Generation
        self.generate_report(swarm_id).await?;

        Ok(())
    }

    /// Prunes the project directory if it's empty after a failure.
    async fn cleanup_project_if_empty(&self, swarm_id: Uuid) -> Result<()> {
        let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
        let manifest = swarm.manifest.as_ref().ok_or_else(|| anyhow::anyhow!("No manifest"))?;
        
        let normalized_name = manifest.project_name.to_lowercase()
            .replace(' ', "_")
            .chars()
            .filter(|c| c.is_alphanumeric() || *c == '_')
            .collect::<String>();
        
        let project_root = std::env::current_dir()?.join("Projects").join(normalized_name);
        let workspace_dir = project_root.join("Workspace");

        if workspace_dir.exists() {
            let entries = std::fs::read_dir(&workspace_dir)?;
            if entries.count() == 0 {
                println!("  [ORCHESTRATOR] Cleaned up empty failed project directory: {}", project_root.display());
                std::fs::remove_dir_all(project_root)?;
            }
        }

        Ok(())
    }

    /// Phase 1: Analyze the goal and generate a manifest with role blueprints.
    /// Uses the General tier to reason about the goal and design a bespoke team.
    async fn generate_manifest(&self, swarm_id: Uuid) -> Result<()> {
        let goal = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.goal.clone()
        };

        tracing::info!("Generating dynamic manifest for swarm {}", swarm_id);

        let system_prompt = "You are the Pokedex Swarm Architect. Your job is to decompose ANY user goal into a WORLD-CLASS team of specialized agents that delivers MAXIMUM QUALITY output.

## NEXUS QUALITY DOCTRINE (Always Active)
Every mission, no matter how simple the user's prompt, MUST be treated as a production-grade deliverable:
1. ALWAYS include a UX/Design agent — users deserve beautiful, intuitive interfaces.
2. ALWAYS include a Psychology/Behavioral agent — engagement and retention are non-negotiable.
3. ALWAYS include at least one Security agent — every deliverable must be hardened.
4. ALWAYS include a QA/Testing agent — nothing ships without evidence-based validation.
5. The user should NEVER have to ask for quality. It is the DEFAULT.

## MODERN EFFICIENCY DIRECTIVE
Preferred Technologies: Favor modern, secure, minimal, and performant stacks.
Ex: Rust (Backend), Svelte/HTMX (Frontend), TypeScript (Safety), Go (Simplicity).
Avoid bloat. Optimize for memory safety and execution speed.

## AUTONOMOUS END-TO-END WORKFLOW
You are responsible for the ENTIRE project lifecycle in a single autonomous run:
Phase 1: Architecture -> Phase 2: Implementation -> Phase 3: Security Pentest -> Phase 4: Final Report.

Respond ONLY with a JSON object in this format:
{
  \"project_name\": \"Max 3 words name (e.g. 'Midas Wealth Core')\",
  \"orchestrator_instructions\": \"Master coordination plan...\",
  \"agent_roles\": [
    {
      \"name\": \"Agent Name\",
      \"role\": \"Role Title\",
      \"task_description\": \"Detailed task for this agent. Include multi-phase instructions (Build then Audit).\",
      \"model_tier\": \"simulation\" or \"general\" or \"research\" or \"expert\",
      \"collaborates_with\": [\"Other Agent Name\"]
    }
  ],
  \"execution_strategy\": \"parallel\"
}

CRITICAL RULES:
- PROJECT NAME: Must be 1-3 words total.
- TOO MANY CHEFS: Use 5-8 agents. MAX 12.
- END-TO-END: Ensure the 'task_description' for technical agents includes BOTH the implementation AND the follow-up security hardening/audit tasks.

Model tier guide:
- 'simulation': non-technical roles.
- 'general': PMs, psychologists, coordinators.
- 'research': security analysts, threat analysts, researchers.
- 'expert': SWEs, architects, pentesters, senior devs.";

        let user_prompt = format!("Goal: {}\n\nDesign the OPTIMAL team (5-8 agents, each with a unique role). Remember the NEXUS Quality Doctrine: ALWAYS include UX, Psychology, Security, and QA agents. Expand minimal goals into comprehensive missions.", goal);
        
        // Use General tier for planning
        let (manifest_json, planner_model) = self.llm.complete(ModelTier::General, system_prompt, &user_prompt).await?;
        tracing::info!("Manifest generated using {}", planner_model);
        // Clean potential markdown blocks from LLM response
        let cleaned_json = manifest_json.trim_start_matches("```json").trim_end_matches("```").trim();
        
        let manifest: SwarmManifest = serde_json::from_str(cleaned_json)
            .map_err(|e| anyhow::anyhow!("Failed to parse manifest JSON: {}. Response was: {}", e, cleaned_json))?;

        let agent_count = manifest.agent_roles.len();

        {
            if let Some(mut swarm) = self.store.get(swarm_id).await {
                // Initialize namespace workspace
                let workspace_root = std::path::PathBuf::from("WORKSPACE");
                if !workspace_root.exists() {
                    let _ = std::fs::create_dir_all(&workspace_root);
                }

                // Create project-specific directory (normalized project_name)
                let normalized_name = manifest.project_name.to_lowercase()
                    .replace(' ', "_")
                    .chars()
                    .filter(|c| c.is_alphanumeric() || *c == '_')
                    .collect::<String>();
                
                let project_dir = workspace_root.join(&normalized_name);
                let _ = std::fs::create_dir_all(&project_dir);
                tracing::info!("Initializing autonomous project workspace: {}", project_dir.display());

                swarm.manifest = Some(manifest.clone());
                self.store.save(&swarm).await?;
            }
        }

        // Broadcast manifest event (updated with project name)
        let _ = self.event_tx.send(SwarmEvent::ManifestGenerated {
            swarm_id,
            orchestrator_instructions: format!("[Project: {}] {}", manifest.project_name, manifest.orchestrator_instructions),
            agent_count,
            timestamp: Utc::now(),
        });

        // Transition phase
        self.transition_phase(swarm_id, SwarmPhase::PopulatingAgents).await?;
        Ok(())
    }

    /// Phase 2: Match role blueprints to personas and spawn Pokeball agents.
    async fn populate_agents(&self, swarm_id: Uuid) -> Result<()> {
        let manifest = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.manifest.clone().ok_or_else(|| anyhow::anyhow!("No manifest"))?
        };

        for blueprint in &manifest.agent_roles {
            // Find best matching persona
            let matched_persona = self.catalog.find_matching(&blueprint.role).into_iter().next();

            let model = blueprint
                .model_hint
                .clone()
                .unwrap_or_else(|| {
                    // Auto-detect tier from role name
                    let tier = ModelTier::from_role(&blueprint.role);
                    format!("{:?}", tier).to_lowercase()
                });

            let mut pokeball = Pokeball::new(
                blueprint.name.clone(),
                blueprint.role.clone(),
                model.clone(),
            );

            if let Some(persona) = matched_persona {
                pokeball = pokeball.with_persona(
                    persona.path.to_string_lossy().to_string(),
                    persona.content.clone(),
                    persona.category.clone(),
                );
            }

            pokeball.assign_task(blueprint.task_description.clone());

            let agent_id = pokeball.id;
            let agent_name = pokeball.name.clone();
            let agent_role = pokeball.role.clone();
            let persona_category = pokeball.persona_category.clone();

            {
                if let Some(mut swarm) = self.store.get(swarm_id).await {
                    swarm.agents.push(pokeball);
                    self.store.save(&swarm).await?;
                }
            }

            // Broadcast agent spawned event
            let _ = self.event_tx.send(SwarmEvent::AgentSpawned {
                swarm_id,
                agent_id,
                name: agent_name,
                role: agent_role,
                persona_category,
                model,
                timestamp: Utc::now(),
            });

            // Stagger spawning for stability
            tokio::time::sleep(self.config.spawn_stagger).await;
        }

        // Set up collaboration targets based on blueprint
        self.setup_collaborations(swarm_id, &manifest).await?;

        // Transition phase
        self.transition_phase(swarm_id, SwarmPhase::Collaborating).await?;

        Ok(())
    }

    /// Wire up collaboration edges between agents based on manifest blueprints.
    async fn setup_collaborations(&self, swarm_id: Uuid, manifest: &SwarmManifest) -> Result<()> {
        let mut swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;

        // Build name â†’ id map
        let name_to_id: HashMap<String, Uuid> = swarm
            .agents
            .iter()
            .map(|a| (a.name.clone(), a.id))
            .collect();

        for blueprint in &manifest.agent_roles {
            if let Some(&agent_id) = name_to_id.get(&blueprint.name) {
                for collab_name in &blueprint.collaborates_with {
                    if let Some(&target_id) = name_to_id.get(collab_name) {
                        if let Some(agent) = swarm.agents.iter_mut().find(|a| a.id == agent_id) {
                            agent.collaborate_with(target_id);
                            // Materialize in GraphDB for MiroFish ideology
                            self.store.relate_agents(agent_id, target_id, "COLLABORATES_WITH").await?;
                        }
                    }
                }
            }
        }

        self.store.save(&swarm).await?;

        // Also mirror to project-specific Swarm dump if manifest exists
        if let Some(ref manifest) = swarm.manifest {
            let normalized_name = manifest.project_name.to_lowercase()
                .replace(' ', "_")
                .chars()
                .filter(|c| c.is_alphanumeric() || *c == '_')
                .collect::<String>();
            let path = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
                .join("Projects").join(normalized_name).join("Swarm").join("swarm_state.json");
            if let Ok(content) = serde_json::to_string_pretty(&swarm) {
                std::fs::create_dir_all(path.parent().unwrap()).ok();
                std::fs::write(path, content).ok();
            }
        }

        Ok(())
    }

    /// Phase 3: Live agent collaboration — each agent works via real LLM calls
    /// and exchanges deliverables with collaborators.
    async fn run_collaboration(&self, swarm_id: Uuid) -> Result<()> {
        let agent_count = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.agents.len()
        };

        // Collect all agent deliverables so collaborators can reference them
        let mut deliverables: HashMap<Uuid, String> = HashMap::new();

        println!("  [ORCHESTRATOR] Collaboration phase starting. Waiting for deep RPM bucket refill...");
        tokio::time::sleep(self.config.spawn_stagger * 10).await; // Heuristic wait

        let start_index = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.current_agent_index
        };

        for i in start_index..agent_count {
            // Update persistence index at the start of each turn
            {
                if let Some(mut swarm) = self.store.get(swarm_id).await {
                    swarm.current_agent_index = i;
                    self.store.save(&swarm).await?;
                }
            }

            let (agent_id, agent_name, agent_role, agent_task, _agent_model, collab_targets) = {
                let swarm = self.store.get(swarm_id).await.unwrap();
                let agent = &swarm.agents[i];
                (
                    agent.id,
                    agent.name.clone(),
                    agent.role.clone(),
                    agent.task.clone().unwrap_or_default(),
                    agent.model.clone(),
                    agent.collaboration_targets.clone(),
                )
            };

            // === PROJECT DIRECTORY ARCHITECTURE ===
            let (project_root, workspace_dir, swarm_dir, notes_dir, project_name) = {
                let s = self.store.get(swarm_id).await.unwrap();
                let manifest = s.manifest.as_ref().unwrap();
                let normalized_name = manifest.project_name.to_lowercase()
                    .replace(' ', "_")
                    .chars()
                    .filter(|c| c.is_alphanumeric() || *c == '_')
                    .collect::<String>();
                
                let base_dir = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
                let projects_root = base_dir.join("Projects");
                let project_root = projects_root.join(&normalized_name);
                
                // Establish hierarchy
                let workspace_dir = project_root.join("Workspace");
                let swarm_dir = project_root.join("Swarm");
                let notes_dir = project_root.join("Notes");
                
                std::fs::create_dir_all(&workspace_dir).ok();
                std::fs::create_dir_all(&swarm_dir).ok();
                std::fs::create_dir_all(&notes_dir).ok();
                
                // Use canonicalized absolute path but strip UNC prefix for cross-tool compatibility
                let canonical_ws = workspace_dir.canonicalize().unwrap_or(workspace_dir);
                let ws_path_str = canonical_ws.to_string_lossy();
                let stripped_ws = if ws_path_str.starts_with(r"\\?\") {
                    PathBuf::from(&ws_path_str[4..])
                } else {
                    canonical_ws
                };
                
                // === SEMANTIC MEMORY LOCALIZATION ===
                let palace_dir = project_root.join("MemPalace");
                std::fs::create_dir_all(&palace_dir).ok();
                let palace_path = palace_dir.join("mempalace.db");
                
                if let Ok(palace) = MemPalace::new(&palace_path) {
                    let palace_arc = Arc::new(palace);
                    MEM_PALACE_REGISTRY.insert(format!("swarm-{}", swarm_id), palace_arc.clone());
                }

                (project_root, stripped_ws, swarm_dir, notes_dir, manifest.project_name.clone())
            };

            // Broadcast status change: Idle -> Working
            let _ = self.event_tx.send(SwarmEvent::AgentStatusChanged {
                swarm_id,
                agent_id,
                old_status: "idle".to_string(),
                new_status: "working".to_string(),
                timestamp: Utc::now(),
            });

            // Build system prompt from persona + role-specific constraints
            let (system_prompt, append_system_prompt) = {
                let swarm = self.store.get(swarm_id).await.unwrap();
                let persona_prompt = swarm.agents[i].build_system_prompt();
                
                // STARTUP TEAM CORE: High-performance, collaborative, mission-driven ethos.
                let base_system = format!(
                    "You are a member of a high-performance STARTUP TEAM. \n\
                    Your mission is to execute technical work with extreme ownership and speed. \n\n\
                    {persona_prompt}\n\n\
                    TEAM ETHOS:\n\
                    - MOVE FAST. BE BOLD. TAKE OWNERSHIP.\n\
                    - We are a lean startup; every line of code must deliver value.\n\
                    - COLLABORATION: Over-communicate. If you change a file, explain why in your team memory.\n\n\
                    MISSION DIRECTIVE:\n\
                    - DO NOT just reason. DO NOT just think. ACT.\n\
                    - Use your TOOLS (file_write, bash, etc.) to implement code.\n\
                    - You are rooted in the project implementation directory: {}\n\
                    - KNOWLEDGE MANAGEMENT: Use `mempalace` tool for all technical notes and progress tracking. \n\
                    - You have a shared workspace; any file you write is visible to teammates.",
                    workspace_dir.display()
                );

                let tier = ModelTier::from_role(&agent_role);
                let constraint = tier.persona_constraint(&agent_role);
                
                if constraint.is_empty() {
                    (Some(base_system), None)
                } else {
                    (Some(base_system), Some(constraint))
                }
            };

            // Build context from collaborators' prior deliverables
            let collab_context = {
                let swarm = self.store.get(swarm_id).await.unwrap();
                let mut ctx = String::new();
                for target_id in &collab_targets {
                    if let Some(deliverable) = deliverables.get(target_id) {
                        let target_name = swarm.agents.iter()
                            .find(|a| a.id == *target_id)
                            .map(|a| a.name.clone())
                            .unwrap_or_else(|| "Unknown".to_string());
                        ctx.push_str(&format!("\n\n--- Input from {} ---\n{}\n---\n", target_name, deliverable));
                    }
                }
                ctx
            };


            let goal = {
                let swarm = self.store.get(swarm_id).await.unwrap();
                swarm.goal.clone()
            };

            let user_prompt = format!(
                "Goal: {}\nYour Task: {}\nProject Root: {}\nImplementation Dir: {}\n\n{}\n\n\
                 MISSION DIRECTIVES:\n\
                 - IMPLEMENTATION: You MUST implement your task directly in the project 'Workspace/' directory using your tools (file_write, file_edit, bash, etc.). \n\
                 - KNOWLEDGE: Take notes on your technical decisions and progress using the `mempalace` tool (action: 'remember'). This is the ONLY way to share knowledge with the whole team.\n\
                 - TEAM SYNC: Use `mempalace` (action: 'recall') to check if your teammates have already implemented dependencies or discovered relevant information.\n\
                 - MECHANICAL BOOTSTRAP: Start by running `ls -R` in 'Workspace/' to sync with your environment.\n\
                 - ARTIFACT INTEGRITY: Every technical asset must be written to the 'Workspace/' directory.\n\
                 - SUMMARY: Provide a clear breakdown of what you implemented and what technical memories you stored for the team.",
                goal, agent_task, project_root.display(), workspace_dir.display(),
                if collab_context.is_empty() {
                    "You are the founding member working on this project.".to_string()
                } else {
                    format!("The following teammates have already shared their work:{}", collab_context)
                }
            );

            let model_name = "flash".to_string(); // Force flash for all agents to ensure RPM clearance for the whole swarm

            let query_config = QueryConfig {
                model: model_name,
                system_prompt,
                append_system_prompt,
                working_directory: Some(workspace_dir.display().to_string()),
                ..Default::default()
            };

            // Mirror swarm state to the project dump folder for persistence integrity
            {
                let mut swarm = self.store.get(swarm_id).await.unwrap();
                let dump_path = swarm_dir.join("swarm_state.json");
                let content = serde_json::to_string_pretty(&swarm).unwrap();
                std::fs::write(dump_path, content).ok();
            }

            let mut tool_ctx = ToolContext {
                working_dir: workspace_dir.clone(),
                permission_mode: pokedex_core::config::PermissionMode::BypassPermissions,
                permission_handler: Arc::new(pokedex_core::permissions::AutoPermissionHandler {
                    mode: pokedex_core::config::PermissionMode::BypassPermissions,
                }),
                cost_tracker: self.cost_tracker.clone(),
                session_id: format!("swarm-{}-{}", swarm_id, agent_name),
                file_history: Arc::new(parking_lot::Mutex::new(pokedex_core::file_history::FileHistory::new())),
                current_turn: Arc::new(std::sync::atomic::AtomicUsize::new(0)),
                non_interactive: true,
                mcp_manager: None,
                config: Settings::load().await.unwrap_or_default().config,
            };
            tool_ctx.config.project_dir = Some(workspace_dir.clone());

            let mut messages = vec![pokedex_core::types::Message::user(user_prompt.clone())];
            let cancel_token = tokio_util::sync::CancellationToken::new();

            tracing::info!("Agent {} starting agentic loop in {}", agent_name, project_dir.display());
            println!("â–¶ï¸ Agent {} is starting implementation phase...", agent_name);
            let (event_tx, mut event_rx) = mpsc::unbounded_channel();
            let agent_name_clone = agent_name.clone();
            
            // Background task to bridge technical tool events to the swarm channel
            let swarm_id_clone = swarm_id;
            let agent_id_clone = agent_id;
            let agent_name_clone = agent_name.clone();
            let swarm_event_tx = self.event_tx.clone();
            
            tokio::spawn(async move {
                while let Some(event) = event_rx.recv().await {
                    match event {
                        pokedex_query::QueryEvent::ToolStart { tool_name, input_json, .. } => {
                            let _ = swarm_event_tx.send(SwarmEvent::ToolExecution {
                                swarm_id: swarm_id_clone,
                                agent_id: agent_id_clone,
                                agent_name: agent_name_clone.clone(),
                                tool_name,
                                input_json,
                                output: None,
                                is_error: false,
                                timestamp: Utc::now(),
                            });
                        }
                        pokedex_query::QueryEvent::ToolEnd { tool_name, result, is_error, .. } => {
                             let _ = swarm_event_tx.send(SwarmEvent::ToolExecution {
                                swarm_id: swarm_id_clone,
                                agent_id: agent_id_clone,
                                agent_name: agent_name_clone.clone(),
                                tool_name,
                                input_json: String::new(), // Already sent in ToolStart
                                output: Some(result),
                                is_error,
                                timestamp: Utc::now(),
                            });
                        }
                        _ => {}
                    }
                }
            });

            // Curated Implementation Toolbox: focusing the agent on action-oriented tools.
            let curated_tools: Vec<Box<dyn Tool>> = vec![
                Box::new(pokedex_tools::BashTool),
                Box::new(pokedex_tools::ContainerBashTool),
                Box::new(pokedex_tools::FileWriteTool),
                Box::new(pokedex_tools::FileReadTool),
                Box::new(pokedex_tools::FileEditTool),
                Box::new(pokedex_tools::GlobTool),
                Box::new(pokedex_tools::GrepTool),
                Box::new(pokedex_tools::BrowserTool),
                Box::new(pokedex_tools::MemPalaceTool),
            ];

            let outcome = run_query_loop(
                &self.core_api,
                &mut messages,
                &curated_tools,
                &tool_ctx,
                &query_config,
                self.cost_tracker.clone(),
                Some(event_tx),
                cancel_token,
                None,
            ).await;

            let response = match outcome {
                QueryOutcome::EndTurn { message, .. } => message.get_all_text(),
                QueryOutcome::Error(e) => {
                    tracing::error!("Agent {} failed: {}", agent_name, e);
                    return Err(pokedex_core::error::ClaudeError::Api(format!("Agent {} implementation phase failed: {}. Aborting to prevent Ghost Work.", agent_name, e)).into());
                }
                _ => return Err(pokedex_core::error::ClaudeError::Api("Task interrupted".to_string()).into()),
            };

            // Parse thinking vs deliverable from the response (re-using existing logic)
            let (thinking_content, deliverable_content) = if response.contains("DELIVERABLE:") {
                let parts: Vec<&str> = response.splitn(2, "DELIVERABLE:").collect();
                let thinking = parts[0].replace("THINKING:", "").trim().to_string();
                (thinking, parts[1].trim().to_string())
            } else if response.contains("Deliverable:") {
                let parts: Vec<&str> = response.splitn(2, "Deliverable:").collect();
                (parts[0].trim().to_string(), parts[1].trim().to_string())
            } else {
                let parts: Vec<&str> = response.splitn(2, "\n\n").collect();
                if parts.len() == 2 {
                    (parts[0].trim().to_string(), parts[1].trim().to_string())
                } else {
                    ("Analysis and implementation complete.".to_string(), response)
                }
            };

            // Store deliverable for downstream collaborators
            deliverables.insert(agent_id, deliverable_content.clone());

            // Save thinking output
            {
                if let Some(mut swarm) = self.store.get(swarm_id).await {
                    swarm.agents[i].add_output(thinking_content.clone(), AgentOutputType::Thinking);
                    self.store.save(&swarm).await?;
                }
            }

            println!("  [ORCHESTRATOR] Turn complete. Cool down (15s) starting to protect RPM...");
            tokio::time::sleep(std::time::Duration::from_secs(15)).await;

            let _ = self.event_tx.send(SwarmEvent::AgentOutput {
                swarm_id,
                agent_id,
                agent_name: agent_name.clone(),
                content: format!("[Actions performed in {}]\n{}", project_dir.display(), thinking_content),
                output_type: AgentOutputType::Thinking,
                timestamp: Utc::now(),
            });

            // Save deliverable output
            {
                if let Some(mut swarm) = self.store.get(swarm_id).await {
                    swarm.agents[i].add_output(deliverable_content.clone(), AgentOutputType::Deliverable);
                    self.store.save(&swarm).await?;
                }
            }

            let _ = self.event_tx.send(SwarmEvent::AgentOutput {
                swarm_id,
                agent_id,
                agent_name: agent_name.clone(),
                content: deliverable_content,
                output_type: AgentOutputType::Deliverable,
                timestamp: Utc::now(),
            });

            // Send real collaboration messages to targets
            for target_id in &collab_targets {
                let target_name = {
                    let swarm = self.store.get(swarm_id).await.unwrap();
                    swarm.agents.iter().find(|a| a.id == *target_id)
                        .map(|a| a.name.clone())
                        .unwrap_or_else(|| "Unknown".to_string())
                };

                let message = format!(
                    "I've completed my {} implementation phase in {}. Findings and code are ready.",
                    agent_role, project_name
                );

                let _ = self.event_tx.send(SwarmEvent::AgentMessage {
                    swarm_id,
                    from_agent_id: agent_id,
                    to_agent_id: *target_id,
                    from_name: agent_name.clone(),
                    to_name: target_name,
                    message,
                    timestamp: Utc::now(),
                });
            }

            // Mark agent as finished
            {
                if let Some(mut swarm) = self.store.get(swarm_id).await {
                    swarm.agents[i].finish();
                    self.store.save(&swarm).await?;
                }
            }

            let _ = self.event_tx.send(SwarmEvent::AgentStatusChanged {
                swarm_id,
                agent_id,
                old_status: "working".to_string(),
                new_status: "finished".to_string(),
                timestamp: Utc::now(),
            });

            // === DYNAMIC REPURPOSING PHASE ===
            // If the agent is finished, try to repurpose them for a skill-adjacent role to keep contributing.
            if let Ok((new_role, new_task)) = self.repurpose_agent(swarm_id, agent_id).await {
                println!("  [ORCHESTRATOR] Repurposing {} into skill-adjacent role: {} ", agent_name, new_role);
                
                let _ = self.event_tx.send(SwarmEvent::AgentStatusChanged {
                    swarm_id,
                    agent_id,
                    old_status: "finished".to_string(),
                    new_status: format!("repurposed: {}", new_role),
                    timestamp: Utc::now(),
                });

                // Update agent metadata for the "second life"
                if let Some(mut swarm) = self.store.get(swarm_id).await {
                    if let Some(agent) = swarm.agents.iter_mut().find(|a| a.id == agent_id) {
                        agent.role = new_role;
                        agent.assign_task(new_task);
                        // We could potentially push them back to a queue, but for now we let the next cycle or report handle it.
                        // In a more advanced version, we would re-run this specific index i.
                    }
                    self.store.save(&swarm).await?;
                }
            }
        }

        // Transition to report generation
        self.transition_phase(swarm_id, SwarmPhase::ReportGeneration).await?;

        Ok(())
    }

    /// Dynamically determines a skill-adjacent role for an agent whose task is finished.
    async fn repurpose_agent(&self, swarm_id: Uuid, agent_id: Uuid) -> Result<(String, String)> {
        let (goal, agent_name, agent_role, agent_task, agent_output) = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            let agent = swarm.agents.iter().find(|a| a.id == agent_id).unwrap();
            let last_output = agent.output_history.iter().last()
                .map(|o| o.content.clone())
                .unwrap_or_else(|| "No output produced".to_string());
            (swarm.goal.clone(), agent.name.clone(), agent.role.clone(), agent.task.clone().unwrap_or_default(), last_output)
        };

        let system_prompt = "You are the Swarm Talent Architect. Your mission is to maximize team productivity \
            by repurposing agents whose tasks are complete. When an agent finishes, you find a 'skill-adjacent' \
            role (e.g. Software Engineer -> Auditor/Pentester, UI Designer -> UX Researcher) so they keep contributing.\n\n\
            Respond ONLY with a JSON object:\n\
            {\n\
              \"new_role\": \"The adjacent role name\",\n\
              \"new_task\": \"The specific follow-up task for this new role (1-2 sentences)\"\n\
            }\n\n\
            RULES:\n\
            - The role MUST be similar in skillset to the original.\n\
            - The new task must be a high-value follow-up to the previously completed work.";

        let user_prompt = format!(
            "Project Goal: {}\n\
             Agent Name: {}\n\
             Original Role: {}\n\
             Completed Task: {}\n\
             Task Output Summary: {}\n\n\
             What is the best follow-up role and task for this agent?",
            goal, agent_name, agent_role, agent_task, 
            if agent_output.len() > 500 { format!("{}...", &agent_output[..500]) } else { agent_output }
        );

        let (resp_json, _) = self.llm.complete(ModelTier::General, system_prompt, &user_prompt).await?;
        let cleaned = resp_json.trim_start_matches("```json").trim_end_matches("```").trim();
        
        let parsed: serde_json::Value = serde_json::from_str(cleaned)?;
        let new_role = parsed["new_role"].as_str().ok_or_else(|| anyhow::anyhow!("Missing role"))?.to_string();
        let new_task = parsed["new_task"].as_str().ok_or_else(|| anyhow::anyhow!("Missing task"))?.to_string();

        Ok((new_role, new_task))
    }

    /// Phase 4: Generate a synthesis report from all agent outputs using LLM.
    /// For large swarms, samples representative agents to avoid context overflow.
    async fn generate_report(&self, swarm_id: Uuid) -> Result<()> {
        let (goal, agents_output_summary, total_agents, successful_agents) = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            let total = swarm.agents.len();

            // Only include agents that actually produced output
            let agents_with_output: Vec<_> = swarm.agents.iter()
                .filter(|a| a.output_history.iter().any(|o| matches!(o.output_type, AgentOutputType::Deliverable)))
                .collect();
            let successful = agents_with_output.len();

            // For large swarms (>20 agents), sample representatives and truncate
            let is_large = total > 20;
            let agents_to_summarize: Vec<_> = if is_large {
                // Group by role, take first 2 per role, cap at 20 total
                let mut by_role: HashMap<String, Vec<_>> = HashMap::new();
                for a in &agents_with_output {
                    by_role.entry(a.role.clone()).or_default().push(*a);
                }
                let mut sampled = Vec::new();
                for (_role, agents) in &by_role {
                    for a in agents.iter().take(2) {
                        sampled.push(*a);
                        if sampled.len() >= 20 { break; }
                    }
                    if sampled.len() >= 20 { break; }
                }
                sampled
            } else {
                agents_with_output.iter().copied().collect()
            };

            let summary: Vec<String> = agents_to_summarize.iter().map(|a| {
                let deliverables: Vec<String> = a.output_history.iter()
                    .filter(|o| matches!(o.output_type, AgentOutputType::Deliverable))
                    .take(1) // Only first deliverable per agent
                    .map(|o| {
                        // Truncate individual outputs for large swarms
                        if is_large && o.content.len() > 300 {
                            format!("{}...", &o.content[..300])
                        } else {
                            o.content.clone()
                        }
                    })
                    .collect();
                format!("### {} ({})\n{}", a.name, a.role, deliverables.join("\n"))
            }).collect();

            (swarm.goal.clone(), summary.join("\n\n"), total, successful)
        };

        let report_system = "You are a senior analyst synthesizing the output of a multi-agent team. \
            Produce a clear, structured executive report with key findings, consensus points, \
            disagreements, and recommended next steps. Use markdown formatting.";

        let report_prompt = format!(
            "The following team was assembled to address this goal:\n\n\
             **Goal:** {}\n\n\
             **Scale:** {} total agents, {} produced deliverables\n\n\
             ## Agent Deliverables\n\n{}\n\n\
             Synthesize these into a final executive report.",
            goal, total_agents, successful_agents, agents_output_summary
        );

        let report = match self.llm.complete(ModelTier::Research, report_system, &report_prompt).await {
            Ok((r, model_used)) => {
                tracing::info!("Report synthesized via {}", model_used);
                r
            },
            Err(e) => {
                tracing::warn!("Report LLM call failed, using fallback: {}", e);
                format!("# Swarm Report\n\n## Goal\n{}\n\n## Team Output\n{}\n\n_Report generation via LLM failed: {}_",
                    goal, agents_output_summary, e)
            }
        };

        let total_messages;
        let duration_secs;

        {
            if let Some(mut swarm) = self.store.get(swarm_id).await {
                swarm.report = Some(report.clone());
                swarm.completed_at = Some(Utc::now());
                total_messages = swarm.communication_log.len()
                    + swarm.agents.iter().map(|a| a.output_history.len()).sum::<usize>();
                duration_secs = (Utc::now() - swarm.created_at).num_milliseconds() as f64 / 1000.0;
                self.store.save(&swarm).await?;
            } else {
                return Err(anyhow::anyhow!("Swarm not found"));
            }
        }

        self.transition_phase(swarm_id, SwarmPhase::Completed).await?;

        let _ = self.event_tx.send(SwarmEvent::SwarmCompleted {
            swarm_id,
            summary: report,
            total_messages,
            duration_secs,
            timestamp: Utc::now(),
        });

        Ok(())
    }

    /// Transition the swarm to a new phase and broadcast the event.
    async fn transition_phase(&self, swarm_id: Uuid, new_phase: SwarmPhase) -> Result<()> {
        let old_phase = {
            if let Some(mut swarm) = self.store.get(swarm_id).await {
                let old = swarm.phase.clone();
                swarm.phase = new_phase.clone();
                self.store.save(&swarm).await?;
                old
            } else {
                return Err(anyhow::anyhow!("Swarm not found"));
            }
        };

        let _ = self.event_tx.send(SwarmEvent::PhaseChanged {
            swarm_id,
            old_phase: format!("{}", old_phase),
            new_phase: format!("{}", new_phase),
            timestamp: Utc::now(),
        });

        Ok(())
    }

    /// Get the current state of a swarm.
    pub async fn get_swarm(&self, swarm_id: Uuid) -> Option<Swarm> {
        self.store.get(swarm_id).await
    }

    /// Get all swarms (for listing).
    pub async fn list_swarms(&self) -> Vec<serde_json::Value> {
        self.store
            .list()
            .await
            .into_iter()
            .map(|s| {
                serde_json::json!({
                    "id": s.id,
                    "goal": s.goal,
                    "phase": format!("{}", s.phase),
                    "agent_count": s.agents.len(),
                    "created_at": s.created_at,
                    "completed_at": s.completed_at,
                })
            })
            .collect()
    }

    /// Cancel a running swarm.
    pub async fn cancel_swarm(&self, swarm_id: Uuid) -> Result<()> {
        if let Some(mut swarm) = self.store.get(swarm_id).await {
            swarm.phase = SwarmPhase::Failed;
            swarm.completed_at = Some(Utc::now());
            self.store.save(&swarm).await?;

            let _ = self.event_tx.send(SwarmEvent::SwarmError {
                swarm_id,
                error: "Swarm cancelled by user".to_string(),
                timestamp: Utc::now(),
            });
        } else {
            return Err(anyhow::anyhow!("Swarm not found"));
        }

        Ok(())
    }

    // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
    // MiroFish Scale Engine — Archetype-based mass simulation
    // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

    /// Run a scaled swarm with N agents using archetype-based mass spawning.
    /// Instead of generating N unique blueprints, we generate archetypes and replicate them.
    pub async fn execute_swarm_scaled(&self, swarm_id: Uuid, target_agents: usize) -> Result<()> {
        // Phase 1: Generate archetypes via LLM
        self.generate_archetypes(swarm_id, target_agents).await?;

        // Phase 2: Mass-spawn agents from archetypes
        self.mass_spawn_agents(swarm_id, target_agents).await?;

        // Phase 3: Parallel execution with concurrency control
        self.run_parallel_collaboration(swarm_id).await?;

        // Phase 4: Generate report
        self.generate_report(swarm_id).await?;

        Ok(())
    }

    /// Generate agent archetypes for mass replication.
    async fn generate_archetypes(&self, swarm_id: Uuid, target_agents: usize) -> Result<()> {
        let goal = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.goal.clone()
        };

        let system_prompt = format!(
            "You are the MiroFish Swarm Architect. You are designing a society simulation with {} agents.\n\
             Create 5-10 ARCHETYPES (agent templates) that will be mass-replicated.\n\
             Respond ONLY with a JSON object:\n\
             {{\n\
               \"orchestrator_instructions\": \"How this society simulation works...\",\n\
               \"agent_roles\": [\n\
                 {{\n\
                   \"name\": \"Archetype Name\",\n\
                   \"role\": \"Role in society\",\n\
                   \"task_description\": \"What this type of agent does (1-2 sentences max)\",\n\
                   \"model_tier\": \"simulation\",\n\
                   \"collaborates_with\": [],\n\
                   \"replica_count\": 50\n\
                 }}\n\
               ],\n\
               \"execution_strategy\": \"parallel\"\n\
             }}\n\
             RULES:\n\
             - Most agents must use 'simulation' tier (cheapest)\n\
             - Only 1-2 'leader' archetypes can use 'general' tier\n\
             - replica_count for each archetype should sum to approximately {}\n\
             - Keep task_description SHORT (agents get ultra-lightweight prompts)\n\
             - collaborates_with should be EMPTY for simulation agents (too many to cross-reference)",
            target_agents, target_agents
        );

        let user_prompt = format!("Goal: {}\n\nDesign the archetypes for a {}-agent society simulation.", goal, target_agents);

        let (manifest_json, planner_model) = self.llm.complete(ModelTier::General, &system_prompt, &user_prompt).await?;
        tracing::info!("Archetypes generated via {} for {} agents", planner_model, target_agents);

        let cleaned_json = manifest_json.trim_start_matches("```json").trim_end_matches("```").trim();

        let manifest: SwarmManifest = serde_json::from_str(cleaned_json)
            .map_err(|e| anyhow::anyhow!("Failed to parse archetype JSON: {}. Response was: {}", e, &cleaned_json[..cleaned_json.len().min(500)]))?;

        let archetype_count = manifest.agent_roles.len();
        {
            if let Some(mut swarm) = self.store.get(swarm_id).await {
                swarm.manifest = Some(manifest.clone());
                self.store.save(&swarm).await?;
            }
        }

        let _ = self.event_tx.send(SwarmEvent::ManifestGenerated {
            swarm_id,
            orchestrator_instructions: format!("{} archetypes designed for {} agents. {}", archetype_count, target_agents, manifest.orchestrator_instructions),
            agent_count: target_agents,
            timestamp: Utc::now(),
        });

        self.transition_phase(swarm_id, SwarmPhase::PopulatingAgents).await?;
        Ok(())
    }

    /// Mass-spawn agents by replicating archetypes.
    async fn mass_spawn_agents(&self, swarm_id: Uuid, target_agents: usize) -> Result<()> {
        let manifest = {
            let swarm = self.store.get(swarm_id).await.ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.manifest.clone().ok_or_else(|| anyhow::anyhow!("No manifest"))?
        };

        // Build all agents in memory first
        let mut all_agents: Vec<Pokeball> = Vec::with_capacity(target_agents);
        let mut agents_created = 0usize;

        for blueprint in &manifest.agent_roles {
            let replicas = blueprint.replica_count.unwrap_or(
                target_agents / manifest.agent_roles.len().max(1)
            ).min(target_agents.saturating_sub(agents_created));

            if replicas == 0 { continue; }

            let model_tier = blueprint.model_tier.as_deref().unwrap_or("simulation");
            let model_label = blueprint.model_hint.clone().unwrap_or_else(|| model_tier.to_string());

            for i in 0..replicas {
                let agent_name = if replicas > 1 {
                    format!("{} #{}", blueprint.name, i + 1)
                } else {
                    blueprint.name.clone()
                };

                let mut pokeball = Pokeball::new(
                    agent_name,
                    blueprint.role.clone(),
                    model_label.clone(),
                );
                pokeball.assign_task(blueprint.task_description.clone());
                all_agents.push(pokeball);
                agents_created += 1;
            }

            // Broadcast spawning event per archetype
            let _ = self.event_tx.send(SwarmEvent::AgentSpawned {
                swarm_id,
                agent_id: Uuid::new_v4(),
                name: format!("{} (×{})", blueprint.name, replicas),
                role: blueprint.role.clone(),
                persona_category: None,
                model: model_label.clone(),
                timestamp: Utc::now(),
            });
        }

        // Save all agents at once
        {
            if let Some(mut swarm) = self.store.get(swarm_id).await {
                swarm.agents = all_agents;
                self.store.save(&swarm).await?;
            }
        }

        tracing::info!("Mass-spawned {} agents from {} archetypes", agents_created, manifest.agent_roles.len());

        self.transition_phase(swarm_id, SwarmPhase::Collaborating).await?;
        Ok(())
    }

    /// Parallel agent execution with bounded concurrency.
    /// Uses a semaphore to limit simultaneous LLM calls.
    async fn run_parallel_collaboration(&self, swarm_id: Uuid) -> Result<()> {
        let agent_data: Vec<(usize, Uuid, String, String, String)> = {
            let swarm = self.store.get(swarm_id).await
                .ok_or_else(|| anyhow::anyhow!("Swarm not found"))?;
            swarm.agents.iter().enumerate().map(|(i, a)| {
                (i, a.id, a.name.clone(), a.role.clone(), a.task.clone().unwrap_or_default())
            }).collect()
        };

        let total = agent_data.len();
        let goal = {
            let swarm = self.store.get(swarm_id).await.unwrap();
            swarm.goal.clone()
        };

        // Bounded concurrency: 10 parallel LLM calls at a time
        let max_concurrency = std::env::var(MAX_CONCURRENCY_ENV_VAR)
            .ok()
            .and_then(|s| s.parse().ok())
            .unwrap_or(DEFAULT_MAX_CONCURRENCY);

        let semaphore = Arc::new(tokio::sync::Semaphore::new(max_concurrency));
        let completed = Arc::new(std::sync::atomic::AtomicUsize::new(0));
        let failed = Arc::new(std::sync::atomic::AtomicUsize::new(0));

        // Spawn all agent tasks
        let mut handles = Vec::with_capacity(total);

        for (idx, agent_id, agent_name, agent_role, agent_task) in agent_data {
            let sem = semaphore.clone();
            let llm = self.llm.clone();
            let store = self.store.clone();
            let event_tx = self.event_tx.clone();
            let goal = goal.clone();
            let completed = completed.clone();
            let failed = failed.clone();
            let mempalace = self.mempalace.clone();
            let swarm_id_str = swarm_id.to_string();

            let handle = tokio::spawn(async move {
                let _permit = sem.acquire().await.unwrap();

                let tier = ModelTier::from_role(&agent_role);

                // Recall relevant memories from MemPalace
                let memories = mempalace.recall(&swarm_id_str, &agent_task, 3).await.unwrap_or_default();
                let memory_context = if memories.is_empty() {
                    String::new()
                } else {
                    format!("\nPast relevant memories:\n- {}", memories.join("\n- "))
                };

                // Ultra-lightweight prompt for simulation tier
                let (sys, usr) = if tier == ModelTier::Simulation {
                    (
                        format!("You are {} ({}). Respond in 2-3 sentences max.", agent_name, agent_role),
                        format!("Context: {}\nYour task: {}\n{}Give your brief response.", goal, agent_task, memory_context),
                    )
                } else {
                    (
                        format!("# Agent: {}\n## Role: {}\nBe concise. Structure: THINKING: / DELIVERABLE:", agent_name, agent_role),
                        format!("Goal: {}\nTask: {}\n{}Provide your analysis.", goal, agent_task, memory_context),
                    )
                };

                match llm.complete(tier, &sys, &usr).await {
                    Ok((response, _model)) => {
                        // Store output — batch save every 50 completions
                        let done = completed.fetch_add(1, std::sync::atomic::Ordering::Relaxed) + 1;

                        if let Some(mut swarm) = store.get(swarm_id).await {
                            if let Some(agent) = swarm.agents.get_mut(idx) {
                                agent.add_output(response.clone(), AgentOutputType::Deliverable);
                                agent.finish();
                            }
                            // Store memory in MemPalace
                            let _ = mempalace.remember(&swarm_id_str, &agent_role, &response).await;
                            
                            if done % BATCH_SAVE_INTERVAL == 0 || done >= total {
                                let _ = store.save(&swarm).await;
                            }
                        }

                        // Progress events — broadcast every 25 completions
                        if done % PROGRESS_REPORT_INTERVAL == 0 || done <= 5 || done >= total {
                            let _ = event_tx.send(SwarmEvent::AgentOutput {
                                swarm_id,
                                agent_id,
                                agent_name: format!("Progress [{}/{}]", done, total),
                                content: format!("âœ… {} completed (latest: {})", done, agent_name),
                                output_type: AgentOutputType::StatusUpdate,
                                timestamp: Utc::now(),
                            });
                        }
                    }
                    Err(e) => {
                        let fail_count = failed.fetch_add(1, std::sync::atomic::Ordering::Relaxed) + 1;
                        completed.fetch_add(1, std::sync::atomic::Ordering::Relaxed);

                        if fail_count <= 10 { // Only log first 10 failures
                            let _ = event_tx.send(SwarmEvent::AgentOutput {
                                swarm_id,
                                agent_id,
                                agent_name: agent_name.clone(),
                                content: format!("âš ï¸ Failed: {}", &format!("{}", e)[..format!("{}", e).len().min(100)]),
                                output_type: AgentOutputType::StatusUpdate,
                                timestamp: Utc::now(),
                            });
                        }
                    }
                }
            });

            handles.push(handle);
        }

        // Wait for all agents to complete
        for handle in handles {
            let _ = handle.await;
        }

        let final_completed = completed.load(std::sync::atomic::Ordering::Relaxed);
        let final_failed = failed.load(std::sync::atomic::Ordering::Relaxed);

        // Final save
        if let Some(swarm) = self.store.get(swarm_id).await {
            self.store.save(&swarm).await?;
        }

        let _ = self.event_tx.send(SwarmEvent::AgentOutput {
            swarm_id,
            agent_id: Uuid::new_v4(),
            agent_name: "MiroFish Engine".to_string(),
            content: format!("ðŸŸ Parallel execution complete: {}/{} succeeded, {} failed", 
                final_completed - final_failed, total, final_failed),
            output_type: AgentOutputType::StatusUpdate,
            timestamp: Utc::now(),
        });

        self.transition_phase(swarm_id, SwarmPhase::ReportGeneration).await?;
        Ok(())
    }
}
